sudo: required
language: cpp
dist: trusty
group: edge

notifications:
  email: false

services:
  docker

env:
  - CMAKE_BUILD_TYPE=Debug CC=clang CXX=clang++ SANITIZER=address
  - CMAKE_BUILD_TYPE=Debug CC=clang CXX=clang++ SANITIZER=memory
  - CMAKE_BUILD_TYPE=Debug CC=clang CXX=clang++ SANITIZER=thread
  - CMAKE_BUILD_TYPE=Debug CC=clang CXX=clang++
  - CMAKE_BUILD_TYPE=Debug CC=gcc CXX=g++
  - CMAKE_BUILD_TYPE=Release CC=clang CXX=clang++
  - CMAKE_BUILD_TYPE=Release CC=gcc CXX=g++

script:
  - export CC=clang CXX=clang++ 
  - ./travis/build.sh
